export const queryKeys = {
  campanias: ['tabmanagement', 'campanias'] as const,
  subcampanias: ['subcampanias'] as const,
  subcampaniasOptions: ['subcampaniasOptions'] as const,
  operadoresOptions: ['operadoresOptions'] as const,
  teamLeaderOptions: ['teamLeaderOptions'] as const,
  paramsBusquedaPorSubcampaña: ['paramsBusquedaPorSubcampaña'] as const,
  paramsBusquedaPorIdYFecha: ['paramsBusquedaPorIdYFecha'] as const,
  filtrosCampos: ['filtrosCampos'] as const,
  filtrosValores: ['filtrosValores'] as const,
  procesamientoCola: ['procesamientoCola'] as const,
  procesamientoLogs: ['procesamientoLogs'] as const,
  resumenDescarga: ['resumenDescarga'] as const,
  resumenSubcampanias: ['resumenSubcampanias'] as const,
  resumenCampanias: ['resumenCampanias'] as const,
  resumenGeneral: ['resumenGeneral'] as const,
  reporteEmpleados: ['reporteEmpleados'] as const,
  procesamientoEventos: ['procesamientoEventos'] as const,
  subcampaniasParametroById: ['subcampaniasParametroById'] as const,
  parametrosGeneralesById: ['parametrosGeneralesById'] as const,
};
