#!/usr/bin/env node
const { spawnSync } = require("child_process");

console.log("🧪 Ejecutando commitlint y validando commit...");
const result = spawnSync("npx", ["--no", "commitlint", "--edit", process.argv[2]], {
  stdio: "inherit"
});

process.exit(result.status);
